version: '3'

services:
  bugzilla: 
    hostname: bugs.local
    build: ./bugzilla
    image: labizbille/docker-bugzilla:1.2
    ports:
      - 80
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DB=bugsdb
    depends_on:
      - mysql-galera
    networks:
      - backend
      - frontend
    labels:
      - "interlock.hostname=bugs"
      - "interlock.domain=local"

  backup: 
    build: ./backup
    image: labizbille/mysql-backup:1.1
    environment:
      - DISCOVERYURL
      - S3_BUCKET
      - BACKUP_NAME=bugzilla1_backup
      - S3_ACCESSID
      - S3_ACCESSKEY
      - MYSQL_HOST=mysql-galera
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DB=bugsdb
    depends_on:
      - mysql-galera
    networks:
      - backend

  mysql-galera:
    image: perconalab/percona-xtradb-cluster:5.6
    environment:
      - DISCOVERYURL
      - MYSQL_ROOT_PASSWORD
      - CLUSTER_NAME=galera
    networks:
      - backend    
      

networks:
  backend:
  frontend:
    external:
      name: to-the-whole-world
