version: '2'

services:
  bugzilla: 
    build: ./bugzilla
    ports:
      - 8015:80
    environment:
      - MYSQL_ROOT_PASSWORD=a3JRlcIJaJ7sPLmkzudG

    depends_on:
      - mysql-galera

  mysql-galera:
    image: perconalab/percona-xtradb-cluster:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=a3JRlcIJaJ7sPLmkzudG
      - CLUSTER_NAME=galera
      
networks:
  default: