version: '2'

services:
  bugzilla: 
    build: ./bugzilla
    ports:
      - 8015:80
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DB=bugsdb

    depends_on:
      - mysql-galera

  backup: 
    build: ./backup
    environment:
      - DISCOVERYURL
      - S3_BUCKET
      - BACKUP_NAME=bugzilla1_backup
      - S3_ACCESSID
      - S3_ACCESSKEY
      - MYSQL_HOST=mysql-galera
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DB=bugsdb
    depends_on:
      - mysql-galera

  mysql-galera:
    image: perconalab/percona-xtradb-cluster:5.6
    environment:
      - MYSQL_ROOT_PASSWORD
      - CLUSTER_NAME=galera
      
networks:
  default: